[build]
  command = "npm run build"
  publish = "dist"

[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ ".cache" ]

[[redirects]]

  from = "/posts/categories/"
  to = "https://pborenstein.dev/posts/categories/"
  status = 301
  force = true

[[redirects]]

  from = "/posts/collections/"
  to = "https://pborenstein.dev/posts/collections/"
  status = 301
  force = true

[[redirects]]

  from = "/posts/dotdotnotation/"
  to = "https://pborenstein.dev/posts/dotdotnotation/"
  status = 301
  force = true

[[redirects]]

  from = "/posts/how-rebase-works/"
  to = "https://pborenstein.dev/posts/how-rebase-works/"
  status = 301
  force = true

[[redirects]]

  from = "/posts/minimal/"
  to = "https://pborenstein.dev/posts/minimal/"
  status = 301
  force = true

[[redirects]]

  from = "/posts/tablehacks/"
  to = "https://pborenstein.dev/posts/tablehacks/"
  status = 301
  force = true
